### ISSUE TITLE
swarm command not working

### ISSUE THREAD

**Issue by jebe2009** [appcelerator/docker-etcd#6]
I use the exact command from the readme.

Tried to get it to run in different environments with docker 17.09 and swarm mode and it always fails with the same error

2017-12-21 12:57:18 I | Running etcd Version: 3.2.11
Git SHA: 1e1dbb2
Go Version: go1.8.5
Go OS/Arch: linux/amd64
setting default auto compaction retention
setting default urls for peers
setting default urls for client
setting initial advertise peer urls and initial cluster
resolving the container IP with Docker DNS...
warning: unable to resolve this container's IP (), switching back to /etc/hosts
found IP in /etc/hosts: 172.17.0.3
building a seeds list for cluster etcd
waiting for the min seeds count (2)
error: couldn't reach the min seeds count after 31 sec, only 0 tasks were found

**Comment by ndegory** [comment]
correct, if not using an overlay network, it will fail, I'll update the README
